include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
    - "**/*.graphql.dart"
    - "**/graphql/*.dart"
    - "**/generated_plugin_registrant.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore
    require_trailing_commas: error
    prefer_single_quotes: error

linter:
  rules:
    avoid_classes_with_only_static_members: false
    avoid_function_literals_in_foreach_calls: false
    avoid_positional_boolean_parameters: false
    avoid_print: false
    avoid_renaming_method_parameters: false
    camel_case_types: true
    constant_identifier_names: false
    depend_on_referenced_packages: false
    directives_ordering: false
    empty_constructor_bodies: true
    # invalid_annotation_target: ignore
    overridden_fields: false
    public_member_api_docs: false
    sized_box_for_whitespace: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    type_annotate_public_apis: false
    require_trailing_commas: true
    prefer_single_quotes: true

# 향후 dart_code_metrics를 사용할 경우 주석을 해제 합니다
# dart_code_metrics:
#   extends:
#     - package:dart_code_metrics_presets/all.yaml
#     - package:dart_code_metrics_presets/metrics_recommended.yaml
#   rules:
#     avoid-long-functions: false